In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
import os; import re

In [10]:
from sklearn.ensemble import GradientBoostingClassifier

In [11]:
from sklearn.cross_validation import KFold

In [12]:
from sklearn.grid_search import GridSearchCV

In [13]:
import time
import datetime

In [14]:
from sklearn.linear_model import LogisticRegressionCV

In [15]:
from sklearn.preprocessing import StandardScaler

In [30]:
from sklearn.decomposition import PCA

In [16]:
features = pd.read_csv('./_features/features.csv', index_col='match_id')

In [11]:
dict_names = os.listdir("./_data/data/dictionaries")

###### create dict of dicts with object description

In [12]:
dicts = dict()
for i,d in enumerate(dict_names):
    dicts[re.sub(r'(.*)\.csv',r'\1',d)] = pd.read_csv('./_data/data/dictionaries/%s' % d)
#print dicts

###### drop final attributes

In [17]:
X = features.drop(features.columns[-6:],1)

###### found skips

In [18]:
counts=X.count()

In [19]:
skips=counts[counts.values < 97230].keys()

###### не в каждом матче FB происходит в первые 5 минут, не в каждом матче летучий курьер приобретается одной из команд в первые 5 минут

In [20]:
skips[[0,-2]]

Index([u'first_blood_time', u'dire_flying_courier_time'], dtype='object')

###### replace na items to ZERO

In [21]:
X_na = X.fillna(0)

###### target var - radiant_win

In [22]:
y=features.radiant_win

###### create cross validator

In [23]:
cv = KFold(y.size,shuffle=True, n_folds=5)

In [24]:
sc=StandardScaler()

Xs=sc.fit_transform(X_na)

In [25]:
keys=list(X.keys()[pd.Series(X.keys()).str.contains('hero', na=False)])

keys.append('lobby_type')

Xdr = X_na.drop(keys,1)

In [26]:
Xdr2=Xdr.drop(X.keys()[pd.Series(X.keys()).str.contains('first_blood_player', na=False)],1)

In [47]:
keys=list(X.keys()[pd.Series(X.keys()).str.contains('hero', na=False)])
#keys.append('lobby_type')
keys=keys+['lobby_type','start_time']+X.keys()[pd.Series(X.keys()).str.contains('first_blood_player', na=False)].tolist()

Xdr2 = X_na.drop(keys,1)

In [48]:
scdr=StandardScaler()

Xsdr=scdr.fit_transform(Xdr2)

In [48]:
est1 = LogisticRegressionCV(Cs=20,cv=cv,scoring='roc_auc',n_jobs=-1)

In [49]:
start_time = datetime.datetime.now()
est1.fit(Xsdr,y)
print 'Time elapsed:', datetime.datetime.now() - start_time

Time elapsed: 0:00:17.918000

In [50]:
est1.scores_[1].max()

0.72075742226010331

In [38]:
est1.scores_[1].max()

0.72075651602744528

In [24]:
ky=list(X.keys()[pd.Series(X.keys()).str.contains('hero', na=False)])

frames = []
for i in ky:
    frames.append(pd.DataFrame(X[i]).rename(index=str, columns={i: "hero"}))

all_hero = pd.concat(frames,ignore_index=True)
N=all_hero['hero'].unique().size

In [28]:
N=112

In [29]:
X_pick = np.zeros((X.shape[0], N))

for i, match_id in enumerate(X.index):
    for p in xrange(5):
        X_pick[i, X.ix[match_id, 'r%d_hero' % (p+1)]-1] = 1
        X_pick[i, X.ix[match_id, 'd%d_hero' % (p+1)]-1] = -1

In [49]:
XX=np.column_stack((Xsdr,X_pick))

In [38]:
X_na

,start_time,lobby_type,r1_hero,r1_level,r1_xp,r1_gold,r1_lh,r1_kills,r1_deaths,r1_items,...,radiant_ward_sentry_count,radiant_first_ward_time,dire_bottle_time,dire_courier_time,dire_flying_courier_time,dire_tpscroll_count,dire_boots_count,dire_ward_observer_count,dire_ward_sentry_count,dire_first_ward_time
match_id,,,,,,,,,,,,,,,,,,,,,
0,1430198770,7,11,5,2098,1489,20,0,0,7,...,0,35,103,-84,221,3,4,2,2,-52
1,1430220345,0,42,4,1188,1033,9,0,1,12,...,0,-20,149,-84,195,5,4,3,1,-5
2,1430227081,7,33,4,1319,1270,22,0,0,12,...,1,-39,45,-77,221,3,4,3,1,13
3,1430263531,1,29,4,1779,1056,14,0,0,5,...,0,-30,124,-80,184,0,4,2,0,27
4,1430282290,7,13,4,1431,1090,8,1,0,8,...,0,46,182,-80,225,6,3,3,0,-16
5,1430284186,1,11,5,1961,1461,19,0,1,6,...,1,-27,2,-86,212,4,4,4,0,-43
8,1430293701,1,8,3,967,1136,7,1,0,8,...,2,-35,6,-86,182,3,6,3,0,10
9,1430299335,7,35,5,2117,1252,16,0,0,6,...,1,26,119,-61,0,2,3,4,0,-15
11,1430308974,1,17,5,1527,906,10,0,1,7,...,1,9,0,-84,226,1,3,4,0,26
12,1430316105,7,15,5,1651,1060,14,0,1,10,...,0,-24,186,-83,195,1,3,2,0,16
14,1430325079,1,22,5,1988,1804,21,1,0,6,...,0,-27,166,-83,0,1,2,2,1,34
15,1430330210,7,27,3,819,763,12,0,2,9,...,3,-19,86,-71,229,0,4,2,0,142
17,1430331421,1,68,2,611,500,0,0,0,6,...,0,14,0,-86,180,0,5,2,0,-43
20,1430341277,1,26,3,739,585,4,0,0,11,...,2,20,245,-83,182,4,3,4,3,22
21,1430342692,1,29,2,430,642,1,0,1,5,...,1,-5,100,-85,205,2,4,1,0,19
22,1430342847,7,53,3,1221,1388,18,0,0,6,...,1,-35,97,-80,181,2,4,3,3,64
23,1430344863,1,20,3,786,1088,3,0,0,9,...,1,8,113,-81,0,4,2,2,0,9
25,1430352015,1,92,4,1435,694,5,0,1,4,...,0,-9,186,-78,215,1,2,2,1,5
26,1430354106,1,26,2,731,500,1,0,1,8,...,1,-23,156,-84,208,2,4,2,2,-15
27,1430355047,1,88,4,1697,975,4,0,0,9,...,1,-28,60,-87,0,4,5,2,0,45
28,1430356392,1,104,4,1276,1259,9,1,1,8,...,0,22,176,-78,180,1,5,3,0,27
29,1430357535,1,3,2,625,789,1,0,0,7,...,0,-20,192,-85,199,5,2,3,0,-29
30,1430358429,7,73,5,2081,2187,19,0,0,9,...,0,7,173,-64,271,2,3,2,0,7
31,1430363469,7,26,0,914,825,4,0,0,4,...,0,0,55,-83,0,5,4,2,0,-15
32,1430365431,1,72,5,1855,2035,35,0,0,11,...,1,12,10,-88,200,1,5,3,0,-28
34,1430372971,1,110,3,802,592,1,0,1,7,...,1,-10,0,-84,181,5,1,2,1,65
35,1430373522,0,36,4,1170,1384,6,2,1,6,...,1,10,121,-85,245,3,4,2,1,-14
36,1430374551,1,58,4,1324,1338,15,0,0,11,...,1,-45,52,-88,183,3,5,3,0,-10
38,1430375522,7,53,4,1299,1218,23,0,0,6,...,0,-7,22,-54,298,2,4,1,1,-15
39,1430377785,1,8,4,1258,1706,21,1,0,6,...,2,-7,162,-85,184,2,3,1,1,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114373,1450217420,0,74,5,1993,1510,21,0,0,4,...,0,0,281,-85,181,1,3,3,0,6
114374,1450220370,1,11,5,1699,1575,17,1,1,8,...,2,-20,0,-82,201,4,5,3,2,-35
114375,1450220378,0,25,5,2258,1698,23,0,0,6,...,0,-48,232,-88,210,7,3,2,0,-31
114376,1450221758,1,71,2,634,500,0,0,1,6,...,1,-17,152,-84,0,6,4,3,0,-11
114379,1450223876,1,68,2,548,671,3,0,0,9,...,1,23,0,-88,184,4,3,3,2,-38
114380,1450224353,7,42,3,891,1682,21,1,0,8,...,0,32,163,-84,276,0,3,4,1,42
114381,1450225074,1,93,3,1682,1611,17,1,0,9,...,0,13,131,-84,0,11,4,1,1,23
114382,1450225077,1,11,4,1538,1407,19,0,1,7,...,0,-1,152,-74,189,2,4,3,1,-15
114383,1450226303,1,59,3,1159,1004,5,1,1,7,...,0,4,136,-86,0,4,3,3,0,93
114384,1450227800,1,100,2,625,585,2,0,1,7,...,1,-32,80,-67,0,3,5,1,0,53
114385,1450227829,1,72,4,1299,1271,19,0,0,10,...,0,-3,0,-63,283,2,6,3,1,-19
114386,1450228956,1,8,3,912,1789,20,2,1,11,...,1,55,179,-85,220,6,4,3,0,26
114387,1450229215,1,1,4,1383,1603,23,0,0,7,...,1,-5,145,-87,0,5,2,2,1,-8
114388,1450231917,7,7,2,763,991,0,1,0,10,...,0,-43,3,-84,183,3,4,2,1,6
114389,1450233506,1,100,3,708,1172,0,2,0,6,...,0,-9,239,-74,235,6,3,2,0,-48
114390,1450242081,7,75,5,1930,1535,13,1,0,5,...,1,-35,103,-86,183,2,1,2,1,-20
114391,1450242546,1,50,3,549,942,6,1,0,11,...,1,-75,0,-88,181,6,3,2,0,-72
114392,1450244314,1,21,5,2387,2085,26,1,0,9,...,1,-24,224,-61,251,3,1,3,1,-3
114394,1450247972,1,1,5,2017,1845,32,0,0,6,...,0,-38,156,-85,198,1,4,2,0,-28
114395,1450248756,1,21,5,2160,2087,25,1,0,9,...,1,3,148,-71,0,6,4,1,0,0
114396,1450249964,1,25,5,2038,1420,21,0,1,6,...,0,33,9,-86,211,2,4,2,0,-23
114397,1450250562,1,11,4,1665,1788,30,0,0,9,...,1,-33,158,-83,181,4,2,3,1,21
114399,1450258083,1,55,5,2049,1864,28,0,0,9,...,1,13,300,-87,209,4,4,4,0,73
114400,1450263508,7,47,5,2097,1910,24,1,1,14,...,1,-34,115,-85,216,7,3,4,0,-11
114401,1450264638,7,100,2,730,1110,0,2,0,9,...,2,-38,106,-87,209,3,2,2,1,-9
114402,1450265551,1,47,4,1706,1198,17,0,1,8,...,0,-29,180,-76,180,3,4,3,0,-24
114403,1450277704,0,43,4,1793,1416,17,0,1,5,...,0,-5,0,-82,0,4,3,2,0,-17
114404,1450291848,1,98,4,1399,540,1,0,0,5,...,2,-32,249,-70,0,1,1,3,1,-15
114405,1450292986,1,100,3,1135,766,6,0,2,6,...,0,-21,254,-85,183,5,3,3,1,-42
114406,1450313370,7,50,3,1053,799,7,0,0,7,...,0,-36,131,-59,0,5,3,2,0,-39

In [226]:
list(range(10,21))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [50]:
estD = LogisticRegressionCV(Cs=15,cv=cv,scoring='roc_auc',n_jobs=-1)

In [51]:
start_time = datetime.datetime.now()
estD.fit(XX,y)
print 'Time elapsed:', datetime.datetime.now() - start_time

Time elapsed: 0:00:50.489000

In [52]:
estD.scores_[1].max()

0.75845107346698071

In [41]:
estD.scores_[1].max()

0.75844020035825577

In [177]:
estD.scores_[1].max()

0.75663728773447603

In [171]:
est.get_params

<bound method LogisticRegressionCV.get_params of LogisticRegressionCV(Cs=15, class_weight=None,
           cv=sklearn.cross_validation.KFold(n=97230, n_folds=5, shuffle=True, random_state=None),
           dual=False, fit_intercept=True, intercept_scaling=1.0,
           max_iter=100, multi_class='ovr', n_jobs=-1, penalty='l2',
           random_state=None, refit=True, scoring='roc_auc',
           solver='lbfgs', tol=0.0001, verbose=0)>

In [46]:
XX.shape

(97230L, 201L)

In [28]:
est = LogisticRegressionCV(Cs=15,cv=cv,scoring='roc_auc',n_jobs=-1)

In [29]:
start_time = datetime.datetime.now()
est.fit(Xs,y)
print 'Time elapsed:', datetime.datetime.now() - start_time

Time elapsed: 0:00:19.256000

In [33]:
est.scores_[1].max()

0.7206460881333201

In [28]:
X_pick.shape

(97230L, 112L)

In [95]:
pest = PCA(n_components=180)
pest.fit(XX.T)
#est.components_
disp=pest.explained_variance_ratio_
disp.sort()
rd=disp[::-1]
rd.cumsum()

array([ 0.04079027,  0.08074931,  0.1203152 ,  0.15971658,  0.19880959,
        0.2378034 ,  0.27649712,  0.31503064,  0.35344849,  0.39162472,
        0.41593185,  0.42990261,  0.44353182,  0.45640762,  0.46917486,
        0.48188077,  0.49447547,  0.5070586 ,  0.51959347,  0.53208532,
        0.54451215,  0.55681476,  0.56751028,  0.57796498,  0.5880962 ,
        0.59765106,  0.60718088,  0.61664377,  0.62608944,  0.63549868,
        0.64485528,  0.65419884,  0.66352509,  0.67281533,  0.68201611,
        0.69115436,  0.70009723,  0.70854641,  0.7168691 ,  0.72491695,
        0.73283184,  0.74062176,  0.74826358,  0.75590125,  0.7635132 ,
        0.77109004,  0.77860634,  0.78608603,  0.79355206,  0.80099485,
        0.80841933,  0.81523581,  0.82165025,  0.82801829,  0.8332951 ,
        0.83829627,  0.84322965,  0.8481287 ,  0.85298991,  0.85772344,
        0.86243577,  0.86710539,  0.87177407,  0.87641204,  0.88101395,
        0.88558019,  0.88974527,  0.89368719,  0.89738322,  0.90092198,
        0.90439698,  0.90763774,  0.91075276,  0.91362218,  0.91628309,
        0.91882102,  0.92125817,  0.92361667,  0.92579235,  0.92790732,
        0.92997652,  0.93192783,  0.93377854,  0.93560476,  0.93739278,
        0.93911765,  0.94071084,  0.94218344,  0.94355003,  0.94486205,
        0.94615632,  0.94740487,  0.94862151,  0.9498048 ,  0.95096158,
        0.95210438,  0.9532258 ,  0.9543232 ,  0.95534899,  0.95635297,
        0.95734077,  0.95826562,  0.95916438,  0.96005823,  0.96092952,
        0.96179319,  0.9626435 ,  0.96347772,  0.96430267,  0.96511219,
        0.96591723,  0.96671557,  0.96750966,  0.96829961,  0.96908547,
        0.96986916,  0.97064594,  0.97141995,  0.97219012,  0.97294772,
        0.97369811,  0.97441989,  0.97510483,  0.97576199,  0.97640883,
        0.97702396,  0.97761361,  0.97819772,  0.9787583 ,  0.97931599,
        0.97986579,  0.98040675,  0.98094297,  0.98146948,  0.98199065,
        0.98251026,  0.98302714,  0.98354121,  0.98405143,  0.98455802,
        0.98506179,  0.9855643 ,  0.98605844,  0.98654502,  0.98701293,
        0.98745364,  0.98788888,  0.98831543,  0.9887298 ,  0.98913299,
        0.98953377,  0.98992707,  0.99031487,  0.99069644,  0.99106818,
        0.9914366 ,  0.99179197,  0.99214384,  0.99249129,  0.99283387,
        0.99316971,  0.99349286,  0.99381286,  0.99412831,  0.99443623,
        0.99472872,  0.99501358,  0.9952928 ,  0.99556787,  0.99583683,
        0.99609778,  0.99635124,  0.99660147,  0.9968482 ,  0.99707963,
        0.99730111,  0.99752087,  0.9977331 ,  0.99793737,  0.99813739])

In [96]:
pcX=pest.components_

In [75]:
pcX.T.shape

(97230L, 70L)

In [84]:
XX.shape

(97230L, 201L)

In [127]:
keys

['lobby_type',
 'r1_hero',
 'r2_hero',
 'r3_hero',
 'r4_hero',
 'r5_hero',
 'd1_hero',
 'd2_hero',
 'd3_hero',
 'd4_hero',
 'd5_hero']

In [190]:
#params_grid={"n_estimators":[10,20,30]}

In [191]:
#gs = GridSearchCV(GradientBoostingClassifier(),param_grid=params_grid,cv=cv,scoring="roc_auc")

In [193]:
times = pd.DataFrame(columns=['n_estimators','time','score'],index=[10,20,30,60])

In [194]:
for n in [10,20,30,60]:
    params_grid={"n_estimators":[n]}
    gs = GridSearchCV(GradientBoostingClassifier(),param_grid=params_grid,cv=cv,scoring="roc_auc")
    start_time = datetime.datetime.now()
    #times['n_estimators:' + gs.param_grid.values()[0][0]] = 
    gs.fit(X_na,y)
    n_est=gs.param_grid.values()[0][0]
    et=(datetime.datetime.now() - start_time).seconds
    sc=gs.best_score_
    times.loc[n_est] = [n_est,et,sc]

#print 'Time elapsed:', datetime.datetime.now() - start_time
times

   n_estimators time     score
10           10   63   0.66469
20           20  126  0.682274
30           30  184  0.689361
60           60  505  0.700428

In [19]:
op_times = pd.DataFrame(columns=['n_estimators','time','score'],index=[10,20,30,60])

In [35]:
for n in [10]:
    params_grid={"n_estimators":[n],'loss':['deviance'],'subsample':[0.2]}
    gs = GridSearchCV(GradientBoostingClassifier(),param_grid=params_grid,cv=cv,scoring="roc_auc")
    start_time = datetime.datetime.now()
    #times['n_estimators:' + gs.param_grid.values()[0][0]] = 
    gs.fit(X_na,y)
    n_est=gs.param_grid.values()[0][0]
    et=(datetime.datetime.now() - start_time).seconds
    sc=gs.best_score_
    
    op_times.loc[n_est] = [n_est,et,sc]

#print 'Time elapsed:', datetime.datetime.now() - start_time
op_times

   n_estimators time     score
10           10   46  0.668749
20          NaN  NaN       NaN
30           30  122  0.684247
60          NaN  NaN       NaN

In [34]:
op_times

   n_estimators time     score
10           10   44  0.670543
20          NaN  NaN       NaN
30           30  122  0.684247
60          NaN  NaN       NaN

In [23]:
op_times

   n_estimators time     score
10          NaN  NaN       NaN
20          NaN  NaN       NaN
30           30  195  0.690125
60          NaN  NaN       NaN